### ISSUE TITLE
[Feature Request]: Making so that the UI does scale with resolution

### ISSUE THREAD

**Issue by KemiYuki** [Lyall/P3RFix#20] opened 2024-02-14 20:14 UTC
### Is your proposal related to a problem?
Here i'm gonna provide some screenshots to show how bad can be the render scaling for the UI: https://imgur.com/a/nI32iaO
This are frames where there is a change in menus, for example going back from the settings, or from the Items menu, look at how the text gets incredibly pixelated.
I've noticed that this doesn't happen on PS5 or Xbox, nor on any other streamed that played on PC from Steam...

Now i want to share the settings that the game was currently running:
Resolution 2560x1440
Shadow: High
Render scale: 125%
Reflections: No
Vsync: on
Framerate: 120

Played on and AMD Radeon RX 6750 XT made by XFX

### Describe the solution you'd like
Would it be possible to make so that you can actually select the resolution of the UI or maybe a toggle that forces the UI to render at the exact resolution of the other models in game

**Comment by SandeMC** [comment] 2024-02-14 20:51
Dupe of https://github.com/Lyall/P3RFix/issues/17

**Closed** 2024-02-14 20:56 UTC
